# --- Namespace ---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
---
# --- Catalog Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: catalog-service
        image: deepaktyagi048/nexus-catalog:latest
        ports:
        - containerPort: 4001
        env:
        - name: PORT
          value: "4001"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: ecommerce
spec:
  selector:
    app: catalog-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001
---
# --- Cart Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: cart-service
        image: deepaktyagi048/nexus-cart:latest
        ports:
        - containerPort: 4002
        env:
        - name: PORT
          value: "4002"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce
spec:
  selector:
    app: cart-service
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 4002
---
# --- Order Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: order-service
        image: deepaktyagi048/nexus-order:latest
        ports:
        - containerPort: 4003
        env:
        - name: PORT
          value: "4003"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 4003
    targetPort: 4003
---
# --- Frontend Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: deepaktyagi048/nexus-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ecommerce
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
